import { projectMetaSchema, type ProjectMeta } from "@/content/schema";

// 목록 순서 = 메인 `$ ls projects/`의 행 순서이자 상세 페이지 이전/다음 순환 순서다.
// 기간·커밋 수는 각 저장소의 git 이력에서 산출한 값이다 (2026-07-27 기준).
const rawProjects = [
  {
    slug: "ku-barrier-free-map",
    order: 1,
    title: "모두의 캠퍼스",
    summary: "배리어프리 캠퍼스 웹 지도 · 고려대 체인지메이커스 선정",
    stackLine: "next.js · supabase",
    badge: { label: "WIP", tone: "accent" },
    preview: "/screenshots/modu-map.png",
    periodStart: "2026.04",
    status: "in-progress",
    role: "1인 개발 (기획·설계·개발·운영)",
    stack: ["Next.js", "TypeScript", "Leaflet", "Supabase", "Cloudflare R2"],
    repoUrl: "https://github.com/dongwoobae/korea-univ-project",
    commits: 188,
    hasCaseStudy: false,
  },
  {
    slug: "ankang-welfare",
    order: 2,
    title: "안강 섬김 복지센터",
    summary: "실고객 홈페이지·CMS · 얼굴 자동 블러",
    stackLine: "next.js · sharp",
    badge: { label: "LIVE", tone: "muted" },
    preview: "/screenshots/sumgim-home.png",
    periodStart: "2026.05",
    periodEnd: "2026.06",
    periodNote: "이후 유지보수",
    status: "operating",
    role: "1인 개발 (기획·설계·개발·운영)",
    stack: [
      "Next.js",
      "TypeScript",
      "Supabase",
      "Cloudflare R2",
      "Sharp",
      "face-api.js",
    ],
    liveUrl: "https://sumgim-welfare.com",
    repoUrl: "https://github.com/dongwoobae/ankang-sumgim",
    commits: 121,
    hasCaseStudy: true,
  },
  {
    slug: "ycc-church",
    order: 3,
    title: "영천중앙교회",
    summary: "교회 홈페이지·CMS · 설교 자동화 · AI 요약",
    stackLine: "next.js · qstash",
    badge: { label: "LIVE", tone: "muted" },
    preview: "/screenshots/ycc-home.png",
    periodStart: "2026.06",
    periodEnd: "2026.07",
    periodNote: "이후 유지보수",
    status: "operating",
    role: "1인 개발 (기획·설계·개발·운영)",
    stack: [
      "Next.js",
      "TypeScript",
      "Neon",
      "Drizzle",
      "Better Auth",
      "QStash",
      "Gemini",
    ],
    liveUrl: "https://www.ycjc.kr",
    repoUrl: "https://github.com/dongwoobae/ycc-website",
    commits: 377,
    hasCaseStudy: true,
  },
  {
    slug: "vehicle-manufacturer",
    order: 4,
    title: "월드ENC.CO",
    summary: "반려견 목욕차 회사 홈페이지 · Wix → 자체 서비스 이관",
    stackLine: "next.js · cloudflare",
    badge: { label: "WIP", tone: "accent" },
    preview: "/screenshots/worldeng-home.png",
    periodStart: "2026.07",
    periodNote: "부품관리 확장은 고객 자료 대기",
    status: "in-progress",
    role: "1인 개발 (기획·설계·개발·운영)",
    stack: [
      "Next.js",
      "TypeScript",
      "Cloudflare Workers",
      "D1",
      "R2",
      "Drizzle",
    ],
    liveUrl: "https://worldengco-website.dongwoobae.workers.dev",
    commits: 64,
    hasCaseStudy: false,
  },
  {
    slug: "herbal-medicine-platform",
    order: 5,
    title: "한약안전사용 플랫폼",
    summary: "복지부 과제 · 공공데이터 3만건+ 통합",
    stackLine: "java · mysql",
    badge: { label: "1인 PM", tone: "muted" },
    preview: "/screenshots/hmsu-home.png",
    periodStart: "2025.01",
    periodEnd: "2025.07",
    status: "completed",
    role: "1인 PM · 개발",
    stack: ["Java", "JSP", "Servlet", "Tomcat", "MySQL"],
    hasCaseStudy: false,
  },
];

// 빌드타임 검증 — 형식이 틀리면 여기서 빌드가 깨진다.
export const projects: ProjectMeta[] = rawProjects.map((project) =>
  projectMetaSchema.parse(project),
);
